server:
  port: 8180
  servlet:
    contextPath: /api/oauth

spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  devtools:
    restart:
      log-condition-evaluation-delta: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: sproutfx-oauth-authorization
    password: sproutfx-oauth-authorization
  datasource:
    url: jdbc:mariadb://mairadb.sproutfx.kr:3306/sproutfx_oauth
    driver-class-name: org.mariadb.jdbc.Driver
    username: sproutfx_oauth
    password: sproutfx_oauth
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true    
    hibernate:      
      ddl-auto: update
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _audit
            store_data_at_delete: true
      hibernate:
        format_sql: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 10
    disable-delta: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
    shutdown:
      enabled: true

sproutfx:
  crypto:
    key-store:
      location: classpath:/keystore/sproutfx-oauth-authorization.jks
      alias: sproutfx-oauth-authorization
      secret: cGxhdGZvcm0tY29uZmln
      password: cGxhdGZvcm0tY29uZmln
  security:
    authorization:
      header: Authorization
      type: Bearer
      provider-code: 0b81c75ee36745df872f29558ffc32d8
      client-code: 0b81c75ee36745df872f29558ffc32d8
      access-token-secret: UXVpYSBvbW5pcywgcXVpIHNlIGV4YWx0YXQsIGh1bWlsaWFiaXR1cjsgZXQsIHF1aSBzZSBodW1pbGlhdCwgZXhhbHRhYml0dXI=
    web:
      ignore:
        patterns:
        - '/actuator/**'
        - '/configuration/ui'
        - '/configuration/security'
        - '/swagger-resources/**'
        - '/swagger-ui.html'
        - '/v3/api-docs'
        - '/webjars/**'
    http:
      authorize-requests:
        permit-all:
          patterns:
          - '/swagger-ui/**'
          - '/authorize'
          - '/token'
          - '/refresh'
  logging:
    identifier: sproutfx-oauth-authorization
    logstash:
      appender-name: LOGSTASH
      async-appender-name: ASYNC_LOGSTASH
      host: 127.0.0.1
      port: 5045
      queue-size: 512