spring:
  application:
    name: sproutfx-oauth-authorization
  profiles:
    active: local
  cloud:
    config:
      enabled: true
  config:
    import:
      - configserver:http://config.sproutfx.kr